[build]
  publish = "/"
  
[[forms]]
  name = "contact"
  success_url = "/thank-you.html"

[[forms]]
  name = "quick-quote"
  success_url = "/thank-you.html"

# Specific redirect for thank-you page (no extension)
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Explicit thank-you.html file
[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200

# Redirect 404 errors to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404 